### ISSUE TITLE
3-steps to activate your linter in vscode

### ISSUE THREAD

**Issue by hbxz** [Jerenyaoyelu/sunshine-waiter#9]
> This process works for me. 
> - Please let me know if you meet any issues or need any help. 
> - Please comment here when you get it done so that I can make sure everyone is OK.

1.  install `prettier` as your dev dependency
      1. Make sure your repo updated to this [dependency_update](https://github.com/Jerenyaoyelu/sunshine-waiter/compare/dependency_update).
      2. `yarn install` or `npm i`.

2.  install the `prettier` extension in your vs-code

![image-20200225111957138](https://user-images.githubusercontent.com/16683831/75203666-db230a00-57c2-11ea-92f7-e0eb802d1cb3.png)

3.  Config your vs-code `settings.json`

    >   How to find your `settings.json`:  In your Mac,  `cmd+shift+p` then type "settings". 

    1.  add following two lines in your `settings.json`

        ``` json
            "editor.formatOnSave": true,
            "editor.defaultFormatter": "esbenp.prettier-vscode",
        ```

    2.  Your settings.json looks like this:

        ``` json
        {
            "editor.formatOnSave": true,
            "editor.defaultFormatter": "esbenp.prettier-vscode",
            "...... your other configuration ": " please don't copy this line" 
        }
        ```

>   [reference: configure-prettier-in-vscode/](https://glebbahmutov.com/blog/configure-prettier-in-vscode/)

**Comment by hbxz** [comment]
One thing I need to mention: by tradition, tab size can be 2 and can be 4. 
HTML files are 4 by default.
The majority in React JSX files are 2. Cause lots of js linters by default are 2.
I pick 2 because we write js more than HTML.

**Comment by hbxz** [comment]
So don't get pissed off when you save a file and dozens of lines got changed for the tab size. 
It will happen only once per file through our project.

**Comment by hbxz** [comment]
Wait for @Annieeee007 to confirm

**Comment by Jerenyaoyelu** [comment]
done
